### ISSUE TITLE
style.py: AttributeError: 'module' object has no attribute 'set_device'

### ISSUE THREAD

**Issue by xaionaro** [fzliu/style-transfer#60]
```
danusya@werewolf:~/style-transfer$ python ./style.py -s ~/****.jpg -c /tmp/****.jpg -v
style.py:main:21:12:25.433 -- Starting style transfer.
Traceback (most recent call last):
  File "./style.py", line 520, in <module>
    main(args)
  File "./style.py", line 481, in main
    caffe.set_device(args.gpu_id)
AttributeError: 'module' object has no attribute 'set_device'
```

**Comment by xaionaro** [comment]
```
danusya@werewolf:~/style-transfer$ python3 ./style.py -s ~/****.jpg -c /tmp/****.jpg -v 
Traceback (most recent call last):
  File "./style.py", line 39, in <module>
    import caffe
  File "/usr/lib/python3/dist-packages/caffe/__init__.py", line 1, in <module>
    from .pycaffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, RMSPropSolver, AdaDeltaSolver, AdamSolver, NCCL, Timer
  File "/usr/lib/python3/dist-packages/caffe/pycaffe.py", line 15, in <module>
    import caffe.io
  File "/usr/lib/python3/dist-packages/caffe/io.py", line 4, in <module>
    from skimage.transform import resize
  File "/usr/lib/python3/dist-packages/skimage/transform/__init__.py", line 1, in <module>
    from .hough_transform import (hough_line, hough_line_peaks,
  File "/usr/lib/python3/dist-packages/skimage/transform/hough_transform.py", line 3, in <module>
    from .. import measure
  File "/usr/lib/python3/dist-packages/skimage/measure/__init__.py", line 2, in <module>
    from ._marching_cubes import (marching_cubes, mesh_surface_area,
  File "/usr/lib/python3/dist-packages/skimage/measure/_marching_cubes.py", line 4, in <module>
    from . import _marching_cubes_cy
ImportError: cannot import name '_marching_cubes_cy'
```

**Comment by xaionaro** [comment]
It's required an instruction "HOW TO INSTALL" :(

**Comment by fzliu** [comment]
What version of Caffe are you using?
